### ISSUE TITLE
Generate aN IDEAL version of the original GTEx C2M2 INSTANCE

### ISSUE THREAD

**Issue by RLC-DCPPC** [nih-cfde/crosscut-metadata#10]
We want a version that looks more like what we think it should look like. Carl's group will produce this (manually?). Then we can work with Oxford so that the instance produced going forward look more like the ideal format.

**Comment by RLC-DCPPC** [comment]
Due 7/12

**Comment by jonathancrabtree** [comment]
My contribution to this (a pared-down example GTEx JSON-LD file) can be found here:
https://github.com/nih-cfde/crosscut-metadata/pull/16
