### ISSUE TITLE
Permanent IDS

### ISSUE THREAD

**Issue by RLC-DCPPC** [nih-cfde/crosscut-metadata#13]
goal: preliminary guide for all contributors to provide Permanent IDs

discuss

local or ?

Datacite?

https://www.nature.com/articles/s41597-019-0031-8/ (thanks Philippe)

**Comment by RLC-DCPPC** [comment]
Our stake in the ground is to use Datacite DOIs for all (file assets, anyway). Ian is investigating (Globus authentication).

Have Ian's group provide update at next meeting.

**Comment by RLC-DCPPC** [comment]
Get DOIs for all our objects (files).

**Comment by RLC-DCPPC** [comment]
Adopt mechanisms from paper referenced above. Assumption at the moment. Feedback to Slack channel.

We can generate them (ISI, CHicago).

Propose granularity next week.

**Comment by abradyIGS** [comment]
[sdata2018259.pdf](https://github.com/nih-cfde/crosscut-metadata/files/3473213/sdata2018259.pdf)
Paper PDF
