### ISSUE TITLE
Populate a DERIVA Catalog from a Globus Automate Flow

### ISSUE THREAD

**Issue by rpwagner** [nih-cfde/crosscut-metadata#18]
Using a set of input metadata in a BDBag, trigger a Globus Automate Flow that populates a DERIVA catalog with sample GTeX metadata.

**Comment by ianfoster** [comment]
This should be in the Automate project, surely?

**Comment by RLC-DCPPC** [comment]
Jonathon Gaff globus automate action provider
Mike Darcy working with Globus login flow and initiate backup/restore actions 
integration should be complete this week.
